---
title: "Cultural evolution in long-billed hermits"
author: <center><font size="4"><a href="https://marce10.github.io/">Marcelo Araya-Salas PhD</a> & <a href="https://scholar.google.com/citations?user=0a8k9T8AAAAJ&hl=es&oi=ao"> Beatriz Willink PhD</a></font></center>
output: github_document
date: <center>`r format(Sys.Date(), "%d-%m-%Y")`</center>
editor_options:
  chunk_output_type: console
---

<!-- Description  -->
Creating long-billed hermit song cultural evolution trees and analyzing evolutionary patterns

*Updated on `r Sys.time()`*

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

# install.packages("rmarkdown")
library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```


## Table of contents
* [General info](#general-info)
  * [Analyses](#Analyses)
    * [To do list](#to-do-list)
      * [Contact](#contact)

## General info

Code used for creating long-billed hermit song cultural evolution trees and analyzing evolutionary patterns.

## Analysis

* [Optimizing cost for MAFFT alignments](https://rpubs.com/marcelo-araya-salas/601010)
* [Aligning song sequences with mafft and prank](https://rpubs.com/marcelo-araya-salas/601065)
* Revbayes models done
* Making trees with RevBayes
* Run revbayes posterior predictions (P3)
* Summarize results revBayes trees
- [MCMC, ML and P3 diagnostics](https://rpubs.com/marcelo-araya-salas/722260)
- [diagnostic plots](lbh_cultural_evolution/tree/master/output/MCMC_diagnostic_plots)
- [tree topology diagnostics](https://rpubs.com/marcelo-araya-salas/709692)

## In progress

*  Tree topology diagnostics 

## To-do list

* New github without output (MAS)
* Add recording methods (MAS)
* Add tree congruence results to github (MAS)
* Add tree congruence to methods (MAS)
* Add Alejo comments to ms
* Run RevBayes with no fossils
* Check aligment convergence

## To-do list 3-12-2024

Marcelo:
- combinar graficos de distribuciones posteriores (decidir si dejar reloj)
- hacer figura 1 (poner espectrograma con panel con secuencia de sonidos sobre el espectrograma)
- materiales suplementarios con ejemplos de codigo para alineamientos y modelos
- hacer un nuevo repositorio (leer el manuscrito y asegurarse q los codigos de cada cosa estan representados)
- Agregar texto suplementario sobre como se midio repetibilidad y agregar valor de repitilibidad al texto principal
- meter en materiales suppl diagnosticos de modelos de reconstruccion (https://rpubs.com/marcelo-araya-salas/722260)
- Rhat y prsf son lo mismo, usar solo uno

- 


## Status
Project is: _in progress_

## Contact
Created by [Marcelo Araya-Salas](https://marceloarayasalas.weebly.com/)


