---
title: <center><font size="6"><b>Tree estimation with Revbayes</b></font></center>
subtitle: <center><font size="4"><b>Long-billed hermit song cultural evolution</b></font></center>
author: <center><font size="4"><a href="http://marceloarayasalas.weebly.com/">Marcelo Araya-Salas, PhD</a></font></center>
date: <center>`r format(Sys.Date(), "%d-%m-%Y")`</center>
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: no
fontsize: 12pt 
editor_options: 
  chunk_output_type: console
---



```{r revbayes create tsvs files, eval = FALSE, echo = TRUE}

#selected leks
sel_leks <- c("SUR", "CCE", "HC1", "BR1", "TR1")

dat <- read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)
yrs <- read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")
alignment	<- c("optimal", "all.equal", "prank") # ER = equal rates

# use all fosils (e.g. SURA-2011, SURA-2012, )
use_all_fossils <- c("all", "early")

# include also fossils before 2008
use_old_fossils <-  c("old", "new")

# create taxa tsv files for revBayes
out <- lapply(unique(sel_leks), function(x)
{

  X <- yrs[yrs$lek == x, ]
  X$taxon <- X$song.type.year

  X$max <- X$min <- max(X$year) - X$year

  # all fossils including before 2008
  all.old <- X <- X[order(X$song.type, X$year), ]

  # write.table(all.old[, c("taxon", "min", "max")], file = paste0("./data/processed/fossils/", x, "_taxa_all_old.tsv"),  sep = "\t", quote = FALSE, row.names = FALSE)
  # # only first appearance of song type/fossil including before 2008
  # early.old <- X[!duplicated(X$song.type), ]
  # 
  # write.table(early.old[, c("taxon", "min", "max")], file = paste0("./data/processed/fossils/", x,  "_taxa_early_old.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  # 
  # Y <- X[X$year > 2000 ]
  # Y <- Y[order(Y$song.type, Y$year), ]
  # 
  # # all fossils excluding before 2000
  # all.new <- Y
  # 
  #   write.table(all.new[, c("taxon", "min", "max")], file = paste0("./data/processed/fossils/", x,  "_taxa_all_new.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  # # only first appearance of song type/fossil including before 2008
  # early.new <- Y[!duplicated(Y$song.type), ]
  # 
  # write.table(early.new[, c("taxon", "min", "max")], file = paste0("./data/processed/fossils/", x,  "_taxa_early_new.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
  
  no.fossils <- all.old[all.old$song.type.year %in% unlist(sapply(unique(all.old$lek), function(x) {
  X <- all.old[all.old$lek == x, ]
  X$song.type.year[X$year == max(X$year)]
  })),
  ]
  
  ## no fossils
  if (x %in% c("BR1", "SUR", "TR1"))
  write.table(no.fossils[, c("taxon", "min", "max")], file = paste0("./data/processed/fossils/", x,  "_taxa_no.fossils.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)

} )

```

# 3 models
- equal rates (mafft aligment)
- optimal (mafft aligment)
- prank

# Each one was run for both different rates for each branch (Uexp) and a single rate (global model)

```{r revbayes loop regular Uexp and global model, eval = FALSE, echo = TRUE}

#selected leks
sel_leks <- c("SUR", "CCE", "HC1", "BR1", "TR1")

dat <-
  read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)
yrs <-
  read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")
alignment	<- c("optimal", "all.equal", "prank") # all.equal = equal rates

# use all fosils (e.g. SURA-2011, SURA-2012, )
use_all_fossils <- c("all", "early")

# include also fossils before 2008
use_old_fossils <-  c("old", "new")

branch_rate_model <- c("global", "Uexp")

# make all possible combinations
grd <-
  expand.grid(
    lek = sel_leks,
    alignment = alignment,
    use_old_fossils = use_old_fossils,
    use_all_fossils = use_all_fossils,
    branch_rate_model = branch_rate_model
  )

templ <- readLines("./source/template.Rev")
algs <- list.files(path = "./data/processed/nexus", pattern = "\\.nex$")

grd <- grd[order(grd$lek),]

# remove "old" combinations without data before 2000s
for (i in sel_leks)
  if (!any(yrs$year[yrs$lek == i] < 2000))
    grd <- grd[!(grd$use_old_fossils == "old" & grd$lek == i),]

grd$output <- apply(grd, 1, paste, collapse = "_")

# remove leks with output
current.output <- list.files(pattern = "posterior.var",
             path = "./output/revbayes",
             recursive = TRUE)

done <- unique(sapply(current.output, function(x)
    paste(strsplit(x, "_", fixed = TRUE, "[[", 1)[[1]][1:5], collapse = "_"), USE.NAMES = FALSE))


grd <- grd[!grd$output %in% done, , drop = FALSE]


for (x in 1:nrow(grd)) {

  print(grd[x,])
  
  yrs.lek <- yrs[yrs$lek == grd$lek[x], ]
  
  if (grd$use_all_fossils[x] == "all")
    last.year.songs <-
    yrs.lek$song.type.year[yrs.lek$year == max(yrs.lek$year)] else {
    last.year.songs <- vector()
    for (i in yrs.lek$song.type[yrs.lek$year == max(yrs.lek$year)]) {
      Y <- yrs.lek[yrs.lek$song.type == i,]
      last.year.songs <-
        c(last.year.songs, Y$song.type.year[which.min(Y$year)])
    }
  }
  
  last.year.songs <- paste0(paste0('"', last.year.songs), '"')
  
  last.year.songs <-
    paste0("clade(", paste0(last.year.songs, collapse = ", "), ")")
  
  nx <-
    paste0(
      "./data/processed/nexus/",
      grd$lek[x],
      "_",
      grd$alignment[x],
      "_",
      grd$use_all_fossils[x],
      "_",
      grd$use_old_fossils[x],
      "_alignment.nex"
    )
  
  tsv <-
    paste0(
      "./data/processed/fossils/",
      grd$lek[x],
      "_taxa_",
      grd$use_all_fossils[x],
      "_",
      grd$use_old_fossils[x],
      ".tsv"
    )
  
  templ <- readLines("./source/template.Rev")
  templ[1] <- gsub("aligment.name", nx, templ[1])
  templ[2] <- gsub("tsv.file", tsv, templ[2])
  templ[4] <-
    gsub("output.base.name",
         file.path("./output/revbayes", grd$output[x]),
         templ[4])
  templ[10] <- gsub("LAST.SONG.TYPES", last.year.songs, templ[10])
  templ[12] <-
    if (grd$branch_rate_model[x] == "global")
      'source("./source/Specimens_control_global.Rev")' else
    'source("./source/Specimens_control_uexp.Rev")'
  
  fl.nm.rb <- paste0("./source/", grd$output[x], ".Rev")
  
  # resave template
  writeLines(templ, con = fl.nm.rb)
  
  cll <-
    paste0("mpirun -np 10 ~/revbayes-master/projects/cmake/rb-mpi ",
           fl.nm.rb)
  
  system(cll)
  
  print(grd[x,])
  
  print("##################### done ############")
  
  print(paste(nrow(grd) - x, "rows left"))
  
  Sys.sleep(10)
}

```

# Run RB on data with no fossils
```{r revbayes loop for data with no fossils, eval = FALSE, echo = TRUE}

#selected leks
sel_leks <- c("SUR", "BR1", "TR1")

dat <-
  read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)
yrs <-
  read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")
alignment	<- c("optimal", "all.equal", "prank") # all.equal = equal rates

branch_rate_model <- c("global", "Uexp")

# make all possible combinations
grd <-
  expand.grid(
    lek = sel_leks,
    alignment = alignment,
    use_old_fossils = "no.fossils",
    use_all_fossils = "full.process",
    branch_rate_model = branch_rate_model
  )

templ <- readLines("./source/template.Rev")
algs <- list.files(path = "./data/processed/nexus", pattern = "\\.nex$")

grd <- grd[order(grd$lek),]

grd$output <- apply(grd, 1, paste, collapse = "_")

# remove leks with output
current.output <- list.files(pattern = "posterior.var",
             path = "./output/revbayes",
             recursive = TRUE)

done <- unique(sapply(current.output, function(x)
    paste(strsplit(x, "_", fixed = TRUE, "[[", 1)[[1]][1:5], collapse = "_"), USE.NAMES = FALSE))


grd <- grd[!grd$output %in% done, , drop = FALSE]


for (x in 1:nrow(grd)) {

  print(grd[x,])
  
  yrs.lek <- yrs[yrs$lek == grd$lek[x], ]

    last.year.songs <-
    yrs.lek$song.type.year[yrs.lek$year == max(yrs.lek$year)] 
  
  last.year.songs <- paste0(paste0('"', last.year.songs), '"')
  
  last.year.songs <-
    paste0("clade(", paste0(last.year.songs, collapse = ", "), ")")
  
  nx <-
    paste0(
      "./data/processed/nexus/",
      grd$lek[x],
      "_",
      grd$alignment[x],
     "_no.fossils_alignment.nex"
    )
  
  tsv <-
    paste0(
      "./data/processed/fossils/",
      grd$lek[x],
      "_taxa_no.fossils.tsv"
    )
  
  templ <- readLines("./source/template.Rev")
  templ[1] <- gsub("aligment.name", nx, templ[1])
  templ[2] <- gsub("tsv.file", tsv, templ[2])
  templ[4] <-
    gsub("output.base.name",
         file.path("./output/revbayes", grd$output[x]),
         templ[4])
  templ[10] <- gsub("LAST.SONG.TYPES", last.year.songs, templ[10])
  templ[12] <-
    if (grd$branch_rate_model[x] == "global")
      'source("./source/no_fossils/Specimens_control_global_BD.Rev")' else
    'source("./source/no_fossils/Specimens_control_uexp_BD.Rev")'
  
  fl.nm.rb <- paste0("./source/no_fossils/", grd$output[x], ".Rev")
  
  # resave template
  writeLines(templ, con = fl.nm.rb)
  
  cll <-
    paste0("mpirun -np 10 ~/revbayes-master/projects/cmake/rb-mpi ",
           fl.nm.rb)
  
  system(cll)
  
  print(grd[x,])
  
  print("##################### done ############")
  
  # print(paste(nrow(grd) - x, "rows left"))
  # 
  # Sys.sleep(10)
}

```

```{r revbayes loop regular Uexp and global model DEPRECATED, eval = FALSE, echo = TRUE}

#selected leks
sel_leks <- c("SUR", "CCE", "HC1", "BR1", "TR1")

dat <- read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)
yrs <- read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")
alignment	<- c("optimal", "all.equal", "prank") # all.equal = equal rates

# use all fosils (e.g. SURA-2011, SURA-2012, )
use_all_fossils <- c("all", "early")

# include also fossils before 2008
use_old_fossils <-  c("old", "new")

branch_rate_model <- c("global", "Uexp")

# make all possible combinations
grd <- expand.grid(lek = sel_leks, alignment = alignment, use_old_fossils = use_old_fossils, use_all_fossils = use_all_fossils, branch_rate_model = branch_rate_model)

templ <- readLines("./source/template.Rev")
algs <- list.files(path = "./data/processed/nexus", pattern = "\\.nex$")

grd <- grd[order(grd$lek), ]

# remove "old" combinations without data before 2000s
for(i in sel_leks)
if (!any(yrs$year[yrs$lek == i] < 2000)) 
  grd <- grd[!(grd$use_old_fossils == "old" & grd$lek == i), ]
  
grd$output <- apply(grd, 1, paste, collapse = "_")

# remove leks with output
current.output <- list.files(pattern = "log$|trees$", path = "./output/revbayes", recursive = TRUE)

done <- unique(sapply(current.output, function(x) paste(strsplit(x, "_",fixed = TRUE, "[[", 1)[[1]][1:5], collapse = "_"), USE.NAMES = FALSE))

grd <- grd[sample(1:nrow(grd)), ]


grd <- grd[!grd$lek %in% c("SUR", "CCE"), ]

grd <- grd[grd$branch_rate_model == "global", ]

for (x in 1:nrow(grd)){
# out <- pbapply::pblapply(1:nrow(grd), cl = 1, function(x){
  
  print(grd[x, ])
  
  yrs.lek <- yrs[yrs$lek == grd$lek[x],]
  
  if (grd$use_all_fossils[x] == "all")
    last.year.songs <- yrs.lek$song.type.year[yrs.lek$year == max(yrs.lek$year)] else {
      last.year.songs <- vector() 
      for (i in yrs.lek$song.type[yrs.lek$year == max(yrs.lek$year)]){
        Y <- yrs.lek[yrs.lek$song.type == i, ]
        last.year.songs <- c(last.year.songs, Y$song.type.year[which.min(Y$year)])
        }
    }
  
  last.year.songs <- paste0(paste0('"', last.year.songs), '"')
  
  last.year.songs <- paste0("clade(", paste0(last.year.songs, collapse = ", "), ")")
  
 nx <- paste0("./data/processed/nexus/", grd$lek[x], "_", grd$alignment[x], "_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], "_alignment.nex")
  
  tsv <- paste0("./data/processed/fossils/", grd$lek[x], "_taxa_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], ".tsv")
  
    templ <- readLines("./source/template.Rev")
    templ[1] <- gsub("aligment.name", nx, templ[1])
    templ[2] <- gsub("tsv.file", tsv, templ[2])
    templ[4] <- gsub("output.base.name", file.path("./output/revbayes", grd$output[x]), templ[4])
    templ[10] <- gsub("LAST.SONG.TYPES", last.year.songs, templ[10])
   
    fl.nm.rb <- paste0("./source/", grd$output[x], ".Rev")
  
    # resave template
    writeLines(templ, con = fl.nm.rb)
  
    # changes on specimen control
    spc_cntrl <- readLines("./source/Specimens_control.Rev")

    # if global
    if (grd$branch_rate_model[x] == "global"){
          spc_cntrl[32] <- '# source("./source/model_UExp.Rev") # UExp relaxed clock'
          spc_cntrl[34] <- 'source("./source/model_Global.Rev") # molecular clock global'
          } else {
          spc_cntrl[32] <- 'source("./source/model_UExp.Rev") # UExp relaxed clock'
          spc_cntrl[34] <- '# source("./source/model_Global.Rev") # molecular clock global'
          }
    
    # resave template
    writeLines(spc_cntrl, con = "./source/Specimens_control.Rev")
  
  # changes on MCMC
    mcmc.rev <- readLines("./source/MCMC.Rev")

    # if SUR and CCE use more runs
    if (grd$lek[x] %in% c("SUR", "CCE")){
          mcmc.rev[30] <- '# mymcmc.burnin(generations=50000,tuningInterval=200)'
          mcmc.rev[31] <- "# mymcmc.run(generations=150000, checkpointInterval=100, checkpointFile=state_name)"
          
          mcmc.rev[34] <- "mymcmc.burnin(generations=100000,tuningInterval=400)"
          mcmc.rev[35] <- "mymcmc.run(generations=300000, checkpointInterval=200, checkpointFile=state_name)"        
          
                    print("generations=100000")

          } else {
          mcmc.rev[30] <- 'mymcmc.burnin(generations=50000,tuningInterval=200)'
          mcmc.rev[31] <- "mymcmc.run(generations=150000, checkpointInterval=100, checkpointFile=state_name)"
          
          mcmc.rev[34] <- "# mymcmc.burnin(generations=100000,tuningInterval=400)"
          mcmc.rev[35] <- "# mymcmc.run(generations=300000, checkpointInterval=200, checkpointFile=state_name)" 
         
                print("generations=50000")
           }
    
    # resave template
    writeLines(mcmc.rev, con = "./source/MCMC.Rev")
  
      
    # cll <- paste0("~/Downloads/revbayes/projects/cmake/rb ", fl.nm.rb)
    cll <- paste0("mpirun -np 10 ~/revbayes-master/projects/cmake/rb-mpi ", fl.nm.rb) 
    
     system(cll)
     
print( "##################### done ############")
     
     Sys.sleep(10)
}
# )

```


```{r revbayes loop global model DEPRECATED, eval = FALSE, echo = TRUE}

#selected leks
sel_leks <- c("SUR", "CCE", "HC1", "BR1", "TR1")

dat <- read.csv("./data/raw/segments_by_song_type.csv", stringsAsFactors = FALSE)
yrs <- read.csv("./data/raw/year_range_by_song_type.csv", stringsAsFactors = FALSE)

yrs$song.type.year <- paste(yrs$song.type, yrs$year, sep = "-")
alignment	<- c("optimal", "all.equal", "prank") # ER = equal rates

# use all fosils (e.g. SURA-2011, SURA-2012, )
use_all_fossils <- c("all", "early")

# include also fossils before 2008
use_old_fossils <-  c("old", "new")

# make all possible combinations
grd <- expand.grid(lek = sel_leks, alignment = alignment, use_old_fossils = use_old_fossils, use_all_fossils = use_all_fossils)

templ <- readLines("./source/template.Rev")
algs <- list.files(path = "./data/processed/nexus", pattern = "\\.nex$")

# algs <- grep(pattern = "optimal", algs, value = TRUE)
grd <- grd[order(grd$lek), ]

# remove "old" combinations without data before 2000s
for(i in sel_leks)
if (!any(yrs$year[yrs$lek == i] < 2000)) 
  grd <- grd[!(grd$use_old_fossils == "old" & grd$lek == i), ]
  
grd$output <- apply(grd, 1, paste, collapse = "_")

grd$output <- paste0(grd$output, "_global")

# remove leks with output
current.output <- list.files(pattern = "log$|trees$", path = "./output/revbayes", recursive = TRUE)

current.output <- grep("global", current.output, value = TRUE)

done <- unique(sapply(current.output, function(x) paste(strsplit(x, "_",fixed = TRUE, "[[", 1)[[1]][1:5], collapse = "_"), USE.NAMES = FALSE))

grd <- grd[!grd$output %in% done, ]

grd <- grd[order(as.character(grd$lek)), ]

out <- pbapply::pblapply(1:nrow(grd), cl = 1, function(x){
  
  yrs.lek <- yrs[yrs$lek == grd$lek[x],]
  
  if (grd$use_all_fossils[x] == "all")
    last.year.songs <- yrs.lek$song.type.year[yrs.lek$year == max(yrs.lek$year)] else {
      last.year.songs <- vector() 
      for (i in yrs.lek$song.type[yrs.lek$year == max(yrs.lek$year)]){
        Y <- yrs.lek[yrs.lek$song.type == i, ]
        last.year.songs <- c(last.year.songs, Y$song.type.year[which.min(Y$year)])
        }
    }
  
  last.year.songs <- paste0(paste0('"', last.year.songs), '"')
  
  last.year.songs <- paste0("clade(", paste0(last.year.songs, collapse = ", "), ")")
  
 nx <- paste0("./data/processed/nexus/", grd$lek[x], "_", grd$alignment[x], "_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], "_alignment.nex")
  
  tsv <- paste0("./data/processed/fossils/", grd$lek[x], "_taxa_", grd$use_all_fossils[x], "_", grd$use_old_fossils[x], ".tsv")
  
    templ <- readLines("./source/template.Rev")
    templ[1] <- gsub("aligment.name", nx, templ[1])
    templ[2] <- gsub("tsv.file", tsv, templ[2])
    templ[4] <- gsub("output.base.name", file.path("./output/revbayes", grd$output[x]), templ[4])
    templ[10] <- gsub("LAST.SONG.TYPES", last.year.songs, templ[10])
   
    fl.nm.rb <- paste0("./source/", grd$output[x], ".Rev")
     
    writeLines(templ, con = fl.nm.rb)
    # cll <- paste0("~/Downloads/revbayes/projects/cmake/rb ", fl.nm.rb)
    cll <- paste0("mpirun -np 10 ~/revbayes-master/projects/cmake/rb-mpi ", fl.nm.rb) 
    
     system(cll)
    # # copy ouput files to  /output/revbayes/
    #   new.output <- list.files(pattern = "log$|trees$", recursive = TRUE)
    # 
    # copied.output <- list.files(pattern = "log$|trees$", path = "./output/revbayes/", recursive = TRUE)
    # 
    # new.output <- new.output[!basename(new.output) %in% copied.output]
    # 
    # if (length(new.output > 0))
    # file.copy(from = new.output, to =file.path("./output/revbayes/", basename(output)))
})

```

```{r move results to another folder, eval = FALSE, echo = TRUE}

# list posterior.var files
posteriors <- list.files(pattern = "posterior.var",
path = "./output/revbayes",
full.names = TRUE)

# get data frame with name of files and models
post_df <- data.frame(full_name = posteriors, model = sapply(basename(posteriors), function(x)
paste(strsplit(x, "_", fixed = TRUE, "[[", 1)[[1]][1:5], collapse = "_"), USE.NAMES = FALSE))

# get date of last modification
posteriors.info <- file.info(post_df$full_name)

# add date time to data frame 
post_df$mtime <- posteriors.info$mtime

# keep only the most recent one for each model
out <- lapply(unique(post_df$model), FUN = function(x){
Y <- post_df[post_df$model == x, ]
W <- Y[which.max(Y$mtime), , drop = FALSE]
return(W)
})

# put back into data frame format
last_models <- do.call(rbind, out)

# get number ID for each model
last_models$model_id <- sapply(last_models$full_name, function(x)
strsplit(x, "_", fixed = TRUE, "[[", 1)[[1]][6], USE.NAMES = FALSE)

# get full names of files to copy
files_to_copy <- list.files(pattern = paste(last_models$model_id, collapse = "|"),
path = "./output/revbayes", full.names = TRUE, recursive = TRUE)

# copy files
copy_res <- file.copy(from = files_to_copy, to = file.path("./output/most_recent_revbayes_models", basename(files_to_copy)), overwrite = TRUE)

# check number of files copied
sum(copy_res)


```

